# Config to define all available collections of histograms
# Previously defined collections can be imported with '<<' or '*'
# Any nested collections created by "<<" or '*' operations will be flattened in sidm_processor.py


pv_base: &pv_base
  - "pv_n"
  - "pv_ndof"
  - "pv_z"
  - "pv_rho"

electron_extra: &electron_extra
  - "electron_GsfEleDEtaInSeedCut"
  - "electron_GsfEleDPhiInCut"
  - "electron_GsfEleEInverseMinusPInverseCut"
  - "electron_GsfEleFull5x5SigmaIEtaIEtaCut"
  - "electron_GsfEleRelPFIsoScaledCut"
  - "electron_GsfEleConversionVetoCut"
  - "electron_GsfEleHadronicOverEMEnergyScaledCut"
  - "electron_GsfEleMissingHitsCut"

electron_extra_2d: &electron_extra_2d
  - "electron_GsfEleDEtaInSeedCut2d"
  - "electron_GsfEleDPhiInCut2d"
  - "electron_GsfEleEInverseMinusPInverseCut2d"
  - "electron_GsfEleRelPFIsoScaledCut2d"
  - "electron_GsfEleFull5x5SigmaIEtaIEtaCut2d"
  - "electron_GsfEleConversionVetoCut2d"
  - "electron_GsfEleHadronicOverEMEnergyScaledCut2d"
  - "electron_GsfEleMissingHitsCut2d"

electron_base: &electron_base
  - "electron_n"
  - "electron_pt"
  - "electron_dxy"
  - "electron_eta_phi"
  - "electron_photonIdx"
  - "electron_dxy"
  - "electron_pfRelIso03_all"
  - "electron_pfRelIso03_all_lowRange"
  - "electron_r9"
  - "electron_scEtOverPt"
  - "electron_sieie"
  - "electron_hoe"
  - "electron_eInvMinusPInv"
  - "electron_lostHits"
  - "electron_deltaEtaSC"

photon_base: &photon_base
  - "photon_n"
  - "photon_pt"
  - "photon_hoe"
  - "photon_sieie"
  - "photon_pfRelIso03_all"
  - "photon_pfRelIso03_chg"
  - "photon_eta_phi"

muon_base: &muon_base
  - "muon_n"
  - "muon_pt"
  - "muon_dxy"
  - "muon_eta_phi"
  - "muon_absD0"
  - "muon_absD0_lowRange"

dsaMuon_base: &dsaMuon_base
  - "dsaMuon_n"
  - "dsaMuon_pt"
  - "dsaMuon_dxy"
  - "dsaMuon_eta_phi"
  - "dsaMuon_absD0"
  - "dsaMuon_absD0_lowRange"

lj_base: &lj_base
  - "lj_n"
  - "lj_pt"
  - "lj_eta_phi"
  - "lj0_pt"
  - "lj1_pt"
  - "lj0_e"
  - "lj1_e"
  - "lj0_dRSpread"
  - "lj1_dRSpread"
  - "lj_electronN"
  - "lj_photonN"
  - "lj_electronPhotonN"
  - "lj_muonN"
  - "lj_dsaMuN"
  - "lj_pfMuN"

mu_lj_base: &mu_lj_base
  - "mu_lj_n"
  - "mu_lj_pt"
  - "mu_lj_muonN"
  - "mu_lj_pfMu_n"
  - "mu_lj_dsaMu_n"
  - "mu_lj_muon_pt"
  - "mu_lj_pfMuon_pt"
  - "mu_lj_dsaMuon_pt"
  - "mu_lj_muon_dxy"
  - "mu_lj_pfMuon_dxy"
  - "mu_lj_dsaMuon_dxy"
  - "mu_lj_muon_dxy_lowRange"
  - "mu_lj_pfMuon_dxy_lowRange"
  - "mu_lj_dsaMuon_dxy_lowRange"
  - "mu_lj_muon_dxy_XLowRange"
  - "mu_lj_pfMuon_dxy_XLowRange"
  - "mu_lj_dsaMuon_dxy_XLowRange"
  - "mu_lj_muon_min_dxy"
  - "mu_lj_pfMuon_min_dxy"
  - "mu_lj_dsaMuon_min_dxy"
  - "mu_lj_muon_min_dxy_XLowRange"
  - "mu_lj_pfMuon_min_dxy_XLowRange"
  - "mu_lj_dsaMuon_min_dxy_XLowRange"
  - "mu_lj_muon_max_dxy"
  - "mu_lj_pfMuon_max_dxy"
  - "mu_lj_dsaMuon_max_dxy"
  - "mu_lj_muon_max_dxy_XLowRange"
  - "mu_lj_pfMuon_max_dxy_XLowRange"
  - "mu_lj_dsaMuon_max_dxy_XLowRange"
  - "mu_lj_pfMu_nTrackerLayers"
  - "mu_lj_dsaMu_trkNumPlanes"
  - "mu_lj_dsaMu_trkNumHits"
  - "mu_lj_dsaMu_trkNumDTHits"
  - "mu_lj_dsaMu_trkNumCSCHits"
  - "mu_lj_dsaMu_nSegments"
  - "mu_lj_dsaMu_nDTSegments"
  - "mu_lj_dsaMu_nCSCSegments"
  - "mu_lj_pfMu_trkNumPlanes"
  - "mu_lj_pfMu_trkNumHits"
  - "mu_lj_pfMu_trkNumDTHits"
  - "mu_lj_pfMu_trkNumCSCHits"
  - "mu_lj_pfMu_trkNumPixelHits"
  - "mu_lj_pfMu_trkNumTrkLayers"
  - "mu_lj_muon_eta_phi"

egm_lj_base: &egm_lj_base
  - "egm_lj_n"
  - "egm_lj_pt"
  - "egm_lj_electronN"
  - "egm_lj_photonN"
  - "egm_lj_electron_pt"
  - "egm_lj_photon_pt"
  - "egm_lj_electron_dxy"
  - "egm_lj_electron_min_dxy"
  - "egm_lj_electron_max_dxy"
  - "egm_lj_electron_dxy_lowRange"
  - "egm_lj_electron_min_dxy_lowRange"
  - "egm_lj_electron_max_dxy_lowRange"
  - "egm_lj_electron_dxy_XLowRange"
  - "egm_lj_electron_min_dxy_XLowRange"
  - "egm_lj_electron_max_dxy_XLowRange"
  - "egm_lj_electron_dxy_XXLowRange"
  - "egm_lj_electron_min_dxy_XXLowRange"
  - "egm_lj_electron_max_dxy_XXLowRange"
  - "egm_lj_electron_dxy_XXXLowRange"
  - "egm_lj_electron_min_dxy_XXXLowRange"
  - "egm_lj_electron_max_dxy_XXXLowRange"
  - "egm_lj_electron_dxy_XXXXLowRange"
  - "egm_lj_electron_min_dxy_XXXXLowRange"
  - "egm_lj_electron_max_dxy_XXXXLowRange"
  - "egm_lj_electron_lostHits"

electron_lj_base: &electron_lj_base
  - "electron_lj_dR"
  - "electron_lj_dR_lowRange"

photon_lj_base: &photon_lj_base
  - "photon_lj_dR"
  - "photon_lj_dR_lowRange"
  - "photon_lj_dR_reallyLowRange"

muon_lj_base: &muon_lj_base
  - "muon_lj_dR"
  - "muon_lj_dR_lowRange"

dsaMuon_lj_base: &dsaMuon_lj_base
  - "dsaMuon_lj_dR"
  - "dsaMuon_lj_dR_lowRange"

lj_lj_base: &lj_lj_base
  - "lj_lj_absdphi"
  - "lj_lj_invmass"
  - "lj_lj_invmass_lowRange"
  - "lj_lj_absdR"
  - "lj_lj_absdeta"
  
isolation_base: &isolation_base  
  - "matched_jet_pt"
  - "mu_matched_jet_pt"
  - "pfmu_matched_jet_pt"
  - "dsamu_matched_jet_pt"
  - "egm_matched_jet_pt"  
  - "electron_matched_jet_pt"
  - "photon_matched_jet_pt"
  
  - "matched_jet_lepfraction"
  - "mu_matched_jet_lepfraction"
  - "pfmu_matched_jet_lepfraction"
  - "dsamu_matched_jet_lepfraction"
  - "egm_matched_jet_lepfraction"
  - "electron_matched_jet_lepfraction"
  - "photon_matched_jet_lepfraction"
  
  - "matched_jet_lj_dR"
  - "mu_matched_jet_lj_dR"
  - "pfmu_matched_jet_lj_dR"
  - "dsamu_matched_jet_lj_dR"
  - "egm_matched_jet_lj_dR"
  - "electron_matched_jet_lj_dR"
  - "photon_matched_jet_lj_dR"
  
  - "lj_isolation"
  - "lj_isolation_zoom"
  - "mu_lj_isolation"
  - "mu_lj_isolation_zoom"
  - "pfmu_lj_isolation"
  - "pfmu_lj_isolation_zoom"
  - "dsamu_lj_isolation"
  - "dsamu_lj_isolation_zoom"
  - "egm_lj_isolation"
  - "egm_lj_isolation_zoom"
  - "electron_lj_isolation"
  - "electron_lj_isolation_zoom"
  - "photon_lj_isolation"
  - "photon_lj_isolation_zoom"

  - "lj_isolation_sum"
  - "dlj_isolation"
  - "lj_isolation_ratio1"
  - "lj_isolation_ratio2"

  - "pfmu_matched_jet_chEmEF"
  - "pfmu_matched_jet_chFPV0EF"
  - "pfmu_matched_jet_chHEF"
  - "pfmu_matched_jet_muEF"
  - "pfmu_matched_jet_neEmEF"
  - "pfmu_matched_jet_neHEF"
  - "dsamu_matched_jet_chEmEF"
  - "dsamu_matched_jet_chFPV0EF"
  - "dsamu_matched_jet_chHEF"
  - "dsamu_matched_jet_muEF"
  - "dsamu_matched_jet_neEmEF"
  - "dsamu_matched_jet_neHEF"
  - "electron_matched_jet_chEmEF"
  - "electron_matched_jet_chFPV0EF"
  - "electron_matched_jet_chHEF"
  - "electron_matched_jet_muEF"
  - "electron_matched_jet_neEmEF"
  - "electron_matched_jet_neHEF"
  - "photon_matched_jet_chEmEF"
  - "photon_matched_jet_chFPV0EF"
  - "photon_matched_jet_chHEF"
  - "photon_matched_jet_muEF"
  - "photon_matched_jet_neEmEF"
  - "photon_matched_jet_neHEF"

muon_crosscleaning_base: &muon_crosscleaning_base  
  - "pfMuon_dsaMuon_dR"
  - "pfMuon_dsaMuon_dR_lowRange"
  - "pfMuon_dsaMuon_dR_lowRange_extrabin"
  - "pfMuon_dsaMuon_dR_XlowRange_extrabin"
  - "pfMuon_dsaMuon_dR_XXlowRange_extrabin"
  - "dsaMuon_pfMuon_dR_lowRange_extrabin"
  - "dsaMuon_pfMuon_dR_XlowRange_extrabin"
  - "dsaMuon_pfMuon_dR_XXlowRange_extrabin"
  - "pfMuonlj_dsaMuonlj_dR"
  - "pfmu_lj_n"
  - "dsamu_lj_n"
  
  - "genAs_toMu_lxy_nosel"
  - "genAs_toMu_lxy_noDSA"
  - "genAs_toMu_lxy_oneDSA"
  - "genAs_toMu_lxy_twoDSA"
  - "genAs_toMu_lxy_noPF"
  - "genAs_toMu_lxy_noPF_noDSA"
  - "genAs_toMu_lxy_noPF_oneDSA"
  - "genAs_toMu_lxy_noPF_twoDSA"
  - "genAs_toMu_lxy_onePF"
  - "genAs_toMu_lxy_onePF_noDSA"
  - "genAs_toMu_lxy_onePF_oneDSA"
  - "genAs_toMu_lxy_onePF_twoDSA"
  - "genAs_toMu_lxy_twoPF"
  - "genAs_toMu_lxy_twoPF_noDSA"
  - "genAs_toMu_lxy_twoPF_oneDSA"
  - "genAs_toMu_lxy_twoPF_twoDSA"
  - "genAs_toMu_lxy_nosel_large"
  - "genAs_toMu_lxy_noDSA_large"
  - "genAs_toMu_lxy_oneDSA_large"
  - "genAs_toMu_lxy_twoDSA_large"
  - "genAs_toMu_lxy_noPF_large"
  - "genAs_toMu_lxy_noPF_noDSA_large"
  - "genAs_toMu_lxy_noPF_oneDSA_large"
  - "genAs_toMu_lxy_noPF_twoDSA_large"
  - "genAs_toMu_lxy_onePF_large"
  - "genAs_toMu_lxy_onePF_noDSA_large"
  - "genAs_toMu_lxy_onePF_oneDSA_large"
  - "genAs_toMu_lxy_onePF_twoDSA_large"
  - "genAs_toMu_lxy_twoPF_large"
  - "genAs_toMu_lxy_twoPF_noDSA_large"
  - "genAs_toMu_lxy_twoPF_oneDSA_large"
  - "genAs_toMu_lxy_twoPF_twoDSA_large"

  - "PFcount"
  - "DSAcount"
  - "matchPFcount"
  - "matchDSAcount"
  
  - "closestDSA_PF_dR"
  - "farthestDSA_PF_dR"
  - "closestDSA_PF_ptRatio"
  - "farthestDSA_PF_ptRatio"
  - "closestDSAplusPF_DP_ptRatio"
  - "farthestDSAplusPF_DP_ptRatio"
  - "DP_DP_mass"
  - "closestDSA_PF_DP_mass"
  - "farthestDSA_PF_DP_mass"
  - "closestDSA_PF_dR_outer"
  - "farthestDSA_PF_dR_outer"

abcd_base: &abcd_base
  - "lj_lj_absdphi_invmass"
  - "lj_lj_absdphi_absdR"
  - "lj_lj_absdphi_absdeta"
  - "lj_lj_absdR_absdeta"
  - "lj_lj_absdR_invmass"
  - "lj_lj_absdeta_invmass"
  - "lj_lj_ptRatio"
  - "lj_lj_absdphi_ptRatio"
  - "lj_lj_absdR_ptRatio"
  - "lj_lj_absdeta_ptRatio"
  - "lj_isolation_lj_pt"
  - "lj_lj_absdphi_isosum"

genE_base: &genE_base
  - "genE_n"
  - "genE_pt"
  - "genE_pt_highRange"
  - "genE_dxy"
  - "genE_dxy_lowRange"
  - "genE_dxy_XLowRange"
  - "genE_dxy_XXLowRange"
  - "genE0_pt"
  - "genE1_pt"
  - "genE0_pt_highRange"
  - "genE1_pt_highRange"
  - "genE_eta_phi"
  - "genE_parent_absPdgId"
  - "genE_genE_dR"
  - "genE_genE_dR_lowRange"
  - "genE_genE_dR_XLowRange"
  - "genE_genE_dR_XXLowRange"
  - "genE_genE_dEta"
  - "genE_genE_dPhi"
  - "genE_genE_dPt"
  - "genE_genE_pt"
  - "electron_genE_dR"
  - "photon_genE_dR"

genMu_base: &genMu_base
  - "genMu_n"
  - "genMu_pt"
  - "genMu_pt_highRange"
  - "genMu_dxy"
  - "genMu_dxy_lowRange"
  - "genMu_dxy_XLowRange"
  - "genMu_dxy_XXLowRange"
  - "genMu0_pt"
  - "genMu1_pt"
  - "genMu0_pt_highRange"
  - "genMu1_pt_highRange"
  - "genMu_eta_phi"
  - "genMu_parent_absPdgId"
  - "genMu_genMu_dR"
  - "genMu_genMu_dR_lowRange"
  - "genMu_genMu_dR_XLowRange"
  - "genMu_genMu_dR_XXLowRange"
  - "genMu_genMu_dEta"
  - "genMu_genMu_dPhi"
  - "genMu_genMu_pt"
  - "muon_genMu_dR"
  - "dsaMuon_genMu_dR"
  - "genMu0_pt_MuMudR"
  - "genMu0_pt_MuMudR_XLowRange"
  - "genMu0_pt_MuMudR_XXLowRange"
  - "genMu0_pt_highRange_MuMudR"
  - "genMu0_pt_highRange_MuMudR_XLowRange"
  - "genMu0_pt_highRange_MuMudR_XXLowRange"
  - "genMu1_pt_MuMudR"
  - "genMu1_pt_MuMudR_XLowRange"
  - "genMu1_pt_MuMudR_XXLowRange"
  - "genMu1_pt_highRange_MuMudR"
  - "genMu1_pt_highRange_MuMudR_XLowRange"
  - "genMu1_pt_highRange_MuMudR_XXLowRange"

genA_base: &genA_base
  - "genAs_n"
  - "genAs_pt"
  - "genAs_pt_highRange"
  - "genAs_eta_phi"
  - "genAs_x_y"
  - "genAs_children_x_y"
  - "genAs_lxy"
  - "genAs_lxy_lowRange"
  - "genAs_pt_lxy"
  - "genAs_lj_dR"
  - "genAs_lj_dR_lowRange"
  - "genAs_children_n"
  - "genAs_children_absPdgId"
  - "genAs_genAs_absdphi"
  - "genAs_matched_lj_lxy"
  - "genAs_matched_lj_pt"
  - "genAs_matched_lj_pt_highRange"
  - "genAs_matched_lj_eta"
  - "genAs_matched_muLj_lxy"
  - "genAs_matched_egmLj_lxy"
  - "genAs_matched_lj_n"

genA_toMu_base: &genA_toMu_base
  - "genAs_toMu_n"
  - "genAs_toMu_pt"
  - "genAs_toMu_pt_highRange"
  - "genAs_toMu_eta"
  - "genAs_toMu_lxy"
  - "genAs_toMu_pt_MuMudR_lowRange"
  - "genAs_toMu_pt_MuMudR_XLowRange"
  - "genAs_toMu_pt_MuMudR_XXLowRange"
  - "genAs_toMu_lxy_MuMudR"
  - "genAs_toMu_lxy_MuMudR_XLowRange"
  - "genAs_toMu_lxy_MuMudR_XXLowRange"
  - "genAs_toMu_lxy_pt_lowRange"
  - "genAs_toMu_matched_lj_lxy"
  - "genAs_toMu_matched_muLj_lxy"
  - "genAs_toMu_matched_muLj_pt"
  - "genAs_toMu_matched_muLj_pt_highRange"
  - "genAs_toMu_matched_muLj_eta"
  - "genAs_toMu_matched_muLj_n"
  - "genAs_toMu_pt_lxy"
  - "genAs_toMu_matched_muLj_pt_lxy"
  - "genAs_toMu_pt_MuMudR_highRange"
  - "genAs_toMu_pt_highRange_MuMudR_lowRange"

genA_toE_base: &genA_toE_base
  - "genAs_toE_n"
  - "genAs_toE_pt"
  - "genAs_toE_lxy"
  - "genAs_toE_lxy_highRange"
  - "genAs_toE_lxy_lowRange"
  - "genAs_toE_lxy_midRange"
  - "genAs_toE_lxy_ecal"
  - "genAs_toE_pt_highRange"
  - "genAs_toE_eta"
  - "genAs_toE_pt_EEdR_lowRange"
  - "genAs_toE_pt_EEdR_XLowRange"
  - "genAs_toE_pt_EEdR_XXLowRange"
  - "genAs_toE_lxy_EEdR"
  - "genAs_toE_lxy_EEdR_XLowRange"
  - "genAs_toE_lxy_EEdR_XXLowRange"
  - "genAs_toE_lxy_pt_lowRange"
  - "genAs_toE_pt_lxy"
  - "genAs_toE_matched_egmLj_pt_lxy"
  - "genAs_toE_lj_dR"
  - "genAs_toE_matched_lj_lxy"
  - "genAs_toE_matched_egmLj_lxy"
  - "genAs_toE_matched_egmLj_lxy_lowRange"
  - "genAs_toE_matched_egmLj_lxy_midRange"
  - "genAs_toE_matched_egmLj_lxy_ecal"
  - "genAs_toE_matched_egmLj_pt"
  - "genAs_toE_matched_egmLj_pt_highRange"
  - "genAs_toE_matched_egmLj_eta"
  - "genAs_toE_matched_egmLj_n"

genA_ratio: &genA_ratio
  - "genA_lj_ptRatio"
  - "genA_egmLj_ptRatio"
  - "genA_oneElectronLj_ptRatio"
  - "genA_onePhotonLj_ptRatio"
  - "genA_twoElectronLj_ptRatio"
  - "genA_twoPhotonLj_ptRatio"
  - "genA_muLj_ptRatio"
  - "genA_egmLj_lxyRatio"
  - "genA_muLj_lxyRatio"

lepton_genA_base: &lepton_genA_base
  - "electron_genA_dR"
  - "photon_genA_dR"
  - "muon_genA_dR"
  - "dsaMuon_genA_dR"
  #- "dsamuon_absd0_genAs_tomu_lxy"
  - "electron_nearGenA_n"
  - "electron_nearGenA_n_genA_lxy"
  - "photon_nearGenA_n"
  - "photon_nearGenA_n_genA_lxy"
  - "muon_nearGenA_n"
  - "muon_nearGenA_n_genA_lxy"
  - "dsaMuon_nearGenA_n"
  - "dsaMuon_nearGenA_n_genA_lxy"

electron_photon_base: &electron_photon_base
  - "electron_photon_dR"

lepton_genLepton_base: &lepton_genLepton_base
  - "dsaMuon_absD0_genMus_dR"
  - "electron_nearGenE_n"
  - "leadingDsaMuon_absD0_genMus_dR"
  - "subLeadingDsaMuon_absD0_genMus_dR"
  - "dsaMuon_absD0_genMus_dR_XLowRange"
  - "leadingDsaMuon_absD0_genMus_dR_XLowRange"
  - "subLeadingDsaMuon_absD0_genMus_dR_XLowRange"
  - "dsaMuon_absD0_genMus_dR_XXLowRange"
  - "leadingDsaMuon_absD0_genMus_dR_XXLowRange"
  - "subLeadingDsaMuon_absD0_genMus_dR_XXLowRange"
  - "dsaMuon_genMu_ptRatio"
  - "dsaMuon0_genMu_ptRatio"
  - "dsaMuon1_genMu_ptRatio"
  - "pfMuon_genMu_ptRatio"
  - "pfMuon0_genMu_ptRatio"
  - "pfMuon1_genMu_ptRatio"
  - "dsaMuon0_genMu0_ptRatio_vs_truept"
  - "muon0_genMu0_ptRatio_vs_truept"
  #- "egmLj_ptRatio_vs_egm_truept"

lepton_genLepton_genA_base: &lepton_genLepton_genA_base
  - "genA_dsaMuonLj_ptRatio"
  - "genA_pfMuonLj_ptRatio"
  - "genA_dsaMuon0Lj_ptRatio"
  - "genA_pfMuon0Lj_ptRatio"
  - "dsaMuon0_genMu0_ptRatio_vs_truelxy"
  - "muon0_genMu0_ptRatio_vs_truelxy"
  - "genMu0_truept_vs_dsaMuon0_lxy"
  - "genMu0_truept_vs_muon0_lxy"
  - "dsaMuon0_muLj_ptRatio_vs_truept"
  - "muon0_muLj_ptRatio_vs_truept"

genA_lj_2d: &genA_lj_2d
  - "mu_lj_genA_ptRatio_vs_recolxy"
  - "egm_lj_genA_ptRatio_vs_recolxy"
  - "mu_lj_genA_ptRatio_vs_truelxy"
  - "egm_lj_genA_ptRatio_vs_truelxy"

gen_base: &gen_base
  - *genE_base
  - *genMu_base
  - *genA_base
  - *genA_toMu_base
  - *genA_toE_base
  - "gen_abspid"

base: &base
  - *pv_base
  - *electron_base
  - *photon_base
  - *muon_base
  - *dsaMuon_base
  - *lj_base
  - *mu_lj_base
  - *egm_lj_base
  - *electron_lj_base
  - *photon_lj_base
  - *muon_lj_base
  - *dsaMuon_lj_base
  - *lj_lj_base
  - *abcd_base
  - *electron_photon_base
  - *isolation_base
  - *muon_crosscleaning_base

base_plus_gen: &base_plus_gen
  - *base
  - *gen_base

base_plus_gen_resolution: &base_plus_gen_resolution
  - *base
  - *gen_base
  - *genA_ratio
  - *genA_lj_2d
  - *lepton_genLepton_base
  - *lepton_genLepton_genA_base

displacement_base: &displacement_base
  - "egm_lj_electronN"
  - "egm_lj_pt"
  - "egm_lj_electronN"
  - "egm_lj_photonN"
  - "egm_lj_electron_dxy"
  - "egm_lj_electron_min_dxy"
  - "egm_lj_electron_max_dxy"
  - "egm_lj_electron_dxy_lowRange"
  - "egm_lj_electron_min_dxy_lowRange"
  - "egm_lj_electron_max_dxy_lowRange"
  - "egm_lj_electron_dxy_XLowRange"
  - "egm_lj_electron_min_dxy_XLowRange"
  - "egm_lj_electron_max_dxy_XLowRange"
  - "egm_lj_electron_dxy_XXLowRange"
  - "egm_lj_electron_min_dxy_XXLowRange"
  - "egm_lj_electron_max_dxy_XXLowRange"
  - "egm_lj_electron_dxy_XXXLowRange"
  - "egm_lj_electron_min_dxy_XXXLowRange"
  - "egm_lj_electron_max_dxy_XXXLowRange"
  - "egm_lj_electron_dxy_XXXXLowRange"
  - "egm_lj_electron_min_dxy_XXXXLowRange"
  - "egm_lj_electron_max_dxy_XXXXLowRange"
  - "egm_lj_electron_lostHits"
  - "mu_lj_pt"
  - "mu_lj_muonN"
  - "mu_lj_pfMu_n"
  - "mu_lj_pfMuon_dxy"
  - "mu_lj_pfMuon_dxy_lowRange"
  - "mu_lj_pfMuon_dxy_XLowRange"
  - "mu_lj_pfMuon_dxy_XLowRange"
  - "mu_lj_pfMuon_min_dxy"
  - "mu_lj_pfMuon_min_dxy_XLowRange"
  - "mu_lj_pfMuon_max_dxy"
  - "mu_lj_pfMuon_max_dxy_XLowRange"
  - "genE_dxy"
  - "genE_dxy_lowRange"
  - "genE_dxy_XLowRange"
  - "genE_dxy_XXLowRange"
  - "genMu_dxy"
  - "genMu_dxy_lowRange"
  - "genMu_dxy_XLowRange"
  - "genMu_dxy_XXLowRange"
  
lj_reco_effi_base: &lj_reco_effi_base
  - "genAs_toE_pt"
  - "genAs_toE_pt_highRange"
  - "genAs_toE_lxy"
  - "genAs_toMu_pt"
  - "genAs_toMu_pt_highRange"
  - "genAs_toMu_lxy"
  - "genE_genE_dR_lowRange"
  - "genE_genE_dR_XLowRange"
  - "genE_genE_dR_XXLowRange"
  - "genMu_genMu_dR_lowRange"
  - "genMu_genMu_dR_XLowRange"
  - "genMu_genMu_dR_XXLowRange"

